import { caseStore } from "../zustand/caseStore";

const useCase = () => {
  const {
    case: caseValue,
    caseList,
    usersList,
    ufValue,
    pdfBase64,
    applicant,
    retailList,
    usersListChat,
    statusList,
    products,
    caseId,
    assistances,
    isLoading,
    isError,
    error,
  } = caseStore((state) => ({
    case: state.case,
    caseId: state.caseId,
    usersList: state.usersList,
    usersListChat: state.usersListChat,
    pdfBase64: state.pdfBase64,
    ufValue: state.ufValue,
    applicant: state.applicant,
    caseList: state.caseList,
    retailList: state.retailList,
    statusList: state.statusList,
    products: state.products,
    assistances: state.assistances,
    isLoading: state.isLoading,
    isError: state.isError,
    error: state.error,
  }));

  const {
    setCase,
    getRetails,
    getStatus,
    getAll,
    getById,
    getUfValue,
    getServicesAndValues,
    getApplicantByRut,
    upsert,
    upsertApplicant,
    getUsersChat,
    resetNoRut,
    reset,
    resetApplicant,
    getPdfContract,
    resetCaseId,
    getUsers,
    resetUserLists,
    resetUserListsChat,
    resetPdf,
  } = caseStore();

  return {
    caseValue,
    caseId,
    applicant,
    pdfBase64,
    usersListChat,
    ufValue,
    caseList,
    retailList,
    statusList,
    products,
    assistances,
    usersList,
    isLoading,
    isError,
    error,
    setCase,
    getRetails,
    getStatus,
    getAll,
    getById,
    getUfValue,
    getServicesAndValues,
    getApplicantByRut,
    upsert,
    getUsersChat,
    upsertApplicant,
    resetNoRut,
    reset,
    getPdfContract,
    resetPdf,
    resetUserLists,
    resetUserListsChat,
    getUsers,
    resetApplicant,
    resetCaseId,
  };
};

export default useCase;
