interface Roles {
  [key: string]: {
    [subKey: string]: string[];
  };
}

export const roles: Roles = {
  slug: {},
  status: {},
  user: {},
  userInsured: {},
  userCompany: {},
  channel: {},
  family: {},
  insured: {},
  beneficiary: {},
  donor: {},
  donation: {},
  company: {},
  customer: {},
  product: {},
  lead: {},
  webhook: {},
  transaction: {},
  agent: {},
  productDescription: {},
  broker: {},
  retail: {},
  userBroker: {},
  userRetail: {},
  district: {
    listAll: ["admin", "user"],
  },
  assistance: {},
  value: {},
  valueType: {},
  contractor: {},
  specialty: {},
  document: {},
  stage: {},
  specialist: {},
  relationship: {},
  partner: {},
  import: {},
  case: {
    create: [],
    uploadDocument: [],
    all: ["admin", "user"],
    getBeneficiaryByRut: [],
    getCaseById: [],
    getAttachById: [],
    getNewCaseNumber: [],
    assignPartner: [],
    getAssignedPartner: [],
    assignSpecialist: [],
    getAssignedSpecialist: [],
    reimburse: [],
    getAssistanceData: [],
    getReimbursment: [],
    getAllReimbursements: [],
    updateReimbursementStatus: [],
    createChatMessage: [],
    getChatByCase: [],
  },
  category: {},
  fileFormat: {},
  field: {},
};
